import tkinter as tk
import tkinter.ttk as ttk
from tkinter import messagebox

main_win = tk.Tk()
main_win.title("テスト用ウィンドウ")
main_win.geometry("600x600")

# 画像読み込み
haruna = tk.PhotoImage(file="C:/Users/user/Desktop/新しい機能を学んでのコピーのコピーのコピー.png")
canvas = tk.Canvas(bg="black", width=1500, height=3000)
canvas.place(x=0, y=0)
canvas.create_image(0, 0, image=haruna, anchor=tk.NW)

# コンボボックスデータの一括定義
combo_data = [
    {
        "label": "クオリティ",
        "options": [
            "細部まで美しく描き込まれた",
            "超リアルな表現",
            "映画のようなライティング",
            "美しく仕上げられた",
            "緻密なディテール",
            "極限までリアル",
            "写真のようなリアリティ",
            "繊細な質感表現",
            "熟練の技で描かれた",
            "息をのむほどのクオリティ",
            "鮮やかな色彩",
            "卓越した技術",
            "鋭いフォーカス",
            "夢のような雰囲気",
            "洗練された仕上がり",
            "輝くような陰影",
            "鮮やかな色調",
            "ダイナミックな光演出",
            "なめらかなグラデーション",
            "優雅な構図",
            "クリスタルのような透明感",
            "非現実的なリアリズム",
            "深みのあるコントラスト",
            "滑らかな描画",
            "鮮明なイメージ表現",
            "完璧な完成度",
            "豊かに描き込まれた",
            "光沢感のある仕上がり",
            "芸術的な輝き",
            "自然なプロポーション",
            "表情豊かな筆遣い",
            "繊細な陰影",
            "生き生きとした質感",
            "印象的なビジュアル",
            "幻想的な光",
            "高解像度",
            "壮大な景観",
            "洗練されたアート技術",
            "微細なニュアンス",
            "圧倒的なリアリズム",
            "魔法のようなリアリズム",
            "透き通るような明瞭さ",
            "カラフルな色使い",
            "精密に作り込まれた",
            "自然な色や形の移行",
            "鮮やかなハイライト",
            "絵画的な質感",
            "自然な光の表現",
            "魅了されるディテール",
            "映画のような奥行き",
            "極限まで鋭いシャープさ",
            "濃密な色の彩度",
            "輝くような色彩",
            "生き生きとした表情",
            "深みのあるリアリズム",
            "光沢のある表面",
            "滑らかな融合",
            "空気感のあるライティング",
            "精密な線画",
            "純粋なビジュアル美",
            "写真クオリティの仕上がり",
            "感情の奥行き",
            "柔らかな光",
            "完璧なライティング",
            "調和の取れたバランス",
            "完璧な精密さ",
            "超細密なディテール",
            "空気感のあるリアリズム",
            "圧倒的な色の深み",
            "繊細に描き込まれた",
            "リアルな陰影表現",
            "現実離れしたディテール",
            "上品な光の使い方",
            "夢のように柔らかい質感",
            "荘厳な光",
            "劇的な光と影",
            "光り輝く雰囲気",
            "圧倒的なスケール感",
            "クリスタルのような質感",
            "超洗練された",
            "鮮やかな物語表現",
            "映画のような色補正",
            "自然な質感",
            "壮大なスタイル",
            "表情豊かなディテール",
            "贅沢な描写",
            "芸術的な繊細さ",
            "細部へのこだわり",
            "洗練された優雅さ",
            "ノスタルジックな雰囲気",
            "超洗練された",
            "幻想的な光の演出",
            "劇的な影",
            "美しいハイライト",
            "夕暮れ時の暖かな光",
            "超クリーンなライン",
            "魔法のようなビジュアル",
            "超高彩度な色彩",
            "活き活きとしたエネルギー",
            "驚くほどの輝き"
        ],
        "mapping": {
            "細部まで美しく描き込まれた": "highly detailed",
            "超リアルな表現": "ultra realistic",
            "映画のようなライティング": "cinematic lighting",
            "美しく仕上げられた": "beautifully rendered",
            "緻密なディテール": "intricate details",
            "極限までリアル": "hyper realistic",
            "写真のようなリアリティ": "photorealistic",
            "繊細な質感表現": "finely textured",
            "熟練の技で描かれた": "masterfully painted",
            "息をのむほどのクオリティ": "breathtaking quality",
            "鮮やかな色彩": "vivid colors",
            "卓越した技術": "exquisite craftsmanship",
            "鋭いフォーカス": "sharp focus",
            "夢のような雰囲気": "dreamlike atmosphere",
            "洗練された仕上がり": "polished finish",
            "輝くような陰影": "luminous shading",
            "鮮やかな色調": "vibrant tones",
            "ダイナミックな光演出": "dynamic lighting",
            "なめらかなグラデーション": "soft gradients",
            "優雅な構図": "elegant composition",
            "クリスタルのような透明感": "crystal clear",
            "非現実的なリアリズム": "surreal realism",
            "深みのあるコントラスト": "deep contrast",
            "滑らかな描画": "smooth rendering",
            "鮮明なイメージ表現": "vivid imagery",
            "完璧な完成度": "flawless execution",
            "豊かに描き込まれた": "richly detailed",
            "光沢感のある仕上がり": "glossy finish",
            "芸術的な輝き": "artistic brilliance",
            "自然なプロポーション": "realistic proportions",
            "表情豊かな筆遣い": "expressive brushwork",
            "繊細な陰影": "delicate shading",
            "生き生きとした質感": "lifelike textures",
            "印象的なビジュアル": "striking visuals",
            "幻想的な光": "ethereal glow",
            "高解像度": "high-resolution",
            "壮大な景観": "majestic scenery",
            "洗練されたアート技術": "refined artistry",
            "微細なニュアンス": "subtle nuances",
            "圧倒的なリアリズム": "intense realism",
            "魔法のようなリアリズム": "magical realism",
            "透き通るような明瞭さ": "pristine clarity",
            "カラフルな色使い": "colorful palette",
            "精密に作り込まれた": "finely crafted",
            "自然な色や形の移行": "smooth transitions",
            "鮮やかなハイライト": "vibrant highlights",
            "絵画的な質感": "painterly texture",
            "自然な光の表現": "natural lighting",
            "魅了されるディテール": "mesmerizing detail",
            "映画のような奥行き": "cinematic depth",
            "極限まで鋭いシャープさ": "ultra sharpness",
            "濃密な色の彩度": "deep color saturation",
            "輝くような色彩": "radiant colors",
            "生き生きとした表情": "vivid expressions",
            "深みのあるリアリズム": "profound realism",
            "光沢のある表面": "glossy surfaces",
            "滑らかな融合": "seamless blending",
            "空気感のあるライティング": "atmospheric lighting",
            "精密な線画": "intricate linework",
            "純粋なビジュアル美": "pure visual beauty",
            "写真クオリティの仕上がり": "photo-grade finish",
            "感情の奥行き": "emotional depth",
            "柔らかな光": "soft glow",
            "完璧なライティング": "perfect lighting",
            "調和の取れたバランス": "harmonious balance",
            "完璧な精密さ": "immaculate precision",
            "超細密なディテール": "hyperfine detail",
            "空気感のあるリアリズム": "atmospheric realism",
            "圧倒的な色の深み": "intense color depth",
            "繊細に描き込まれた": "delicately detailed",
            "リアルな陰影表現": "realistic shading",
            "現実離れしたディテール": "surreal detail",
            "上品な光の使い方": "elegant lighting",
            "夢のように柔らかい質感": "dreamy softness",
            "荘厳な光": "majestic lighting",
            "劇的な光と影": "dramatic lighting",
            "光り輝く雰囲気": "luminous atmosphere",
            "圧倒的なスケール感": "epic scale",
            "クリスタルのような質感": "crystal textures",
            "超洗練された": "super refined",
            "鮮やかな物語表現": "vivid storytelling",
            "映画のような色補正": "cinematic color grading",
            "自然な質感": "natural textures",
            "壮大なスタイル": "grandiose style",
            "表情豊かなディテール": "expressive detail",
            "贅沢な描写": "luxurious rendering",
            "芸術的な繊細さ": "artistic finesse",
            "細部へのこだわり": "meticulous detailing",
            "洗練された優雅さ": "refined elegance",
            "ノスタルジックな雰囲気": "nostalgic atmosphere",
            "幻想的な光の演出": "fantastical lighting",
            "劇的な影": "dramatic shadows",
            "美しいハイライト": "beautiful highlights",
            "夕暮れ時の暖かな光": "golden hour glow",
            "超クリーンなライン": "ultra clean lines",
            "魔法のようなビジュアル": "enchanted visuals",
            "超高彩度な色彩": "hyper-saturated colors",
            "活き活きとしたエネルギー": "lively energy",
            "驚くほどの輝き": "stunning brilliance"
        },
        "add_comma": False
    },
    {
        "label": "キャラ1",
        "options": [
            "少年",
            "少女",
            "青年男性",
            "青年女性",
            "中年男性",
            "中年女性",
            "高齢男性",
            "高齢女性",
            "ビジネスマン",
            "ビジネスウーマン",
            "学生",
            "小学校教師",
            "大学教授",
            "医者",
            "看護師",
            "警察官",
            "消防士",
            "科学者",
            "アスリート",
            "バレリーナ",
            "ロックミュージシャン",
            "ジャズシンガー",
            "演劇俳優",
            "映画監督",
            "写真家",
            "パイロット",
            "キャビンアテンダント",
            "シェフ",
            "パティシエ",
            "農家",
            "漁師",
            "工場労働者",
            "ソフトウェアエンジニア",
            "グラフィックデザイナー",
            "建築家",
            "探偵",
            "弁護士",
            "裁判官",
            "政治家",
            "ジャーナリスト",
            "書店員",
            "カフェ店員",
            "花屋店員",
            "美容師",
            "メイクアップアーティスト",
            "モデル",
            "ファッションデザイナー",
            "宝石商",
            "お菓子屋さん",
            "ウェイター",
            "ウェイトレス",
            "サラリーマン",
            "OL（オフィスレディ）",
            "ニート",
            "主婦",
            "主夫",
            "保育士",
            "動物看護師",
            "獣医師",
            "バーテンダー",
            "漫画家",
            "小説家",
            "イラストレーター",
            "アニメーター",
            "声優",
            "ラジオパーソナリティ",
            "通訳者",
            "翻訳家",
            "ヨガインストラクター",
            "フィットネストレーナー",
            "サッカー選手",
            "バスケットボール選手",
            "テニスプレイヤー",
            "ゴルファー",
            "レーサー",
            "スキー選手",
            "プロゲーマー",
            "ストリーマー",
            "SNSインフルエンサー",
            "ブロガー",
            "縁日屋台店員",
            "着物職人",
            "伝統芸能師",
            "剣道家",
            "柔道家",
            "空手家",
            "武道家",
            "書道家",
            "茶道家",
            "華道家",
            "旅行ガイド",
            "バックパッカー",
            "冒険家",
            "山岳ガイド",
            "ライフセーバー",
            "環境活動家",
            "ボランティア",
            "NGOスタッフ",
            "料理研究家",
            "お笑い芸人"
        ],
        "mapping": {
            "少年": "young boy",
            "少女": "young girl",
            "青年男性": "young man",
            "青年女性": "young woman",
            "中年男性": "middle-aged man",
            "中年女性": "middle-aged woman",
            "高齢男性": "elderly man",
            "高齢女性": "elderly woman",
            "ビジネスマン": "businessman",
            "ビジネスウーマン": "businesswoman",
            "学生": "student",
            "小学校教師": "elementary school teacher",
            "大学教授": "university professor",
            "医者": "doctor",
            "看護師": "nurse",
            "警察官": "police officer",
            "消防士": "firefighter",
            "科学者": "scientist",
            "アスリート": "athlete",
            "バレリーナ": "ballerina",
            "ロックミュージシャン": "rock musician",
            "ジャズシンガー": "jazz singer",
            "演劇俳優": "stage actor",
            "映画監督": "film director",
            "写真家": "photographer",
            "パイロット": "pilot",
            "キャビンアテンダント": "flight attendant",
            "シェフ": "chef",
            "パティシエ": "pastry chef",
            "農家": "farmer",
            "漁師": "fisherman",
            "工場労働者": "factory worker",
            "ソフトウェアエンジニア": "software engineer",
            "グラフィックデザイナー": "graphic designer",
            "建築家": "architect",
            "探偵": "detective",
            "弁護士": "lawyer",
            "裁判官": "judge",
            "政治家": "politician",
            "ジャーナリスト": "journalist",
            "書店員": "bookstore clerk",
            "カフェ店員": "cafe staff",
            "花屋店員": "florist",
            "美容師": "hair stylist",
            "メイクアップアーティスト": "makeup artist",
            "モデル": "model",
            "ファッションデザイナー": "fashion designer",
            "宝石商": "jeweler",
            "お菓子屋さん": "confectioner",
            "ウェイター": "waiter",
            "ウェイトレス": "waitress",
            "サラリーマン": "office worker",
            "OL（オフィスレディ）": "office lady",
            "ニート": "unemployed youth",
            "主婦": "housewife",
            "主夫": "househusband",
            "保育士": "nursery teacher",
            "動物看護師": "veterinary nurse",
            "獣医師": "veterinarian",
            "バーテンダー": "bartender",
            "漫画家": "manga artist",
            "小説家": "novelist",
            "イラストレーター": "illustrator",
            "アニメーター": "animator",
            "声優": "voice actor",
            "ラジオパーソナリティ": "radio host",
            "通訳者": "interpreter",
            "翻訳家": "translator",
            "ヨガインストラクター": "yoga instructor",
            "フィットネストレーナー": "fitness trainer",
            "サッカー選手": "soccer player",
            "バスケットボール選手": "basketball player",
            "テニスプレイヤー": "tennis player",
            "ゴルファー": "golfer",
            "レーサー": "race car driver",
            "スキー選手": "skier",
            "プロゲーマー": "pro gamer",
            "ストリーマー": "streamer",
            "SNSインフルエンサー": "social media influencer",
            "ブロガー": "blogger",
            "縁日屋台店員": "festival stall vendor",
            "着物職人": "kimono craftsman",
            "伝統芸能師": "traditional performer",
            "剣道家": "kendo practitioner",
            "柔道家": "judo practitioner",
            "空手家": "karate practitioner",
            "武道家": "martial artist",
            "書道家": "calligrapher",
            "茶道家": "tea ceremony master",
            "華道家": "flower arrangement master",
            "旅行ガイド": "tour guide",
            "バックパッカー": "backpacker",
            "冒険家": "adventurer",
            "山岳ガイド": "mountain guide",
            "ライフセーバー": "lifeguard",
            "環境活動家": "environmental activist",
            "ボランティア": "volunteer worker",
            "NGOスタッフ": "NGO worker",
            "料理研究家": "culinary researcher",
            "お笑い芸人": "comedian"
        },
        "add_comma": True
    },

    {
        "label": "キャラ2",
        "options": [
            "謎めいた魔術師",
            "サイボーグ暗殺者",
            "優雅なバレリーナ",
            "退役した兵士",
            "物憂げな詩人",
            "ゴシックな貴婦人",
            "砂漠を彷徨う旅人",
            "呪われた剣士",
            "未来的なパイロット",
            "スチームパンク整備士",
            "盲目の予言者",
            "復讐に燃える霊",
            "路上のマジシャン",
            "量子ハッカー",
            "不死の神官",
            "アンドロイド護衛",
            "王家の側近",
            "エリート狙撃手",
            "時空の旅人",
            "ゴシックなギタリスト",
            "夢見る図書館司書",
            "呪われた錬金術師",
            "都会の忍者",
            "高位の巫女",
            "失墜した騎士",
            "テレパシー能力を持つ子供",
            "吸血鬼の貴族",
            "部族のシャーマン",
            "星間を逃げる逃亡者",
            "氷の魔術師",
            "悪魔狩人",
            "森の精霊導師",
            "神秘的な僧侶",
            "クローン実験体",
            "反逆の王女",
            "闘技場の剣闘士",
            "霊に取り憑かれたバイオリニスト",
            "戦闘用アンドロイド",
            "忘れられた王位継承者",
            "魂の収集者",
            "呪いを受けた考古学者",
            "水中のスパイ",
            "影の工作員",
            "念動力の戦士",
            "心を読む科学者",
            "仮面の反乱軍リーダー",
            "幽霊船の船長",
            "幻術の使い手",
            "無法のガンマン",
            "ペスト医師",
            "逃走中のアンドロイド",
            "戦傷を負った退役軍人",
            "仮面の自警団員",
            "ゴシックな舞踏家",
            "星から追放された者",
            "ドラゴンの調教師",
            "呪われた王子",
            "炎の魔女",
            "記憶を奪う者",
            "盲目の女剣士",
            "神秘的なハッカー",
            "超能力探偵",
            "堕天使",
            "夢の解読者",
            "人形に取り憑かれた使い手",
            "霊媒師",
            "装甲の戦術家",
            "機械仕掛けの発明家",
            "貴族の替え玉",
            "月の巫女",
            "宇宙船の航行士",
            "裏切られた将軍",
            "霊の囁きを聞く者",
            "量子空間の旅人",
            "感情を失ったアンドロイド",
            "孤独な天文学者",
            "不死の放浪者",
            "次元を渡る者",
            "氷上の舞姫",
            "操られた兵士",
            "猫の目を持つ盗賊",
            "呪われた音楽家",
            "高貴な祓魔師",
            "クローンの反乱リーダー",
            "魔女狩り師",
            "裏切られた王国の守護者",
            "異種混血の人間",
            "魔法使いの無法者",
            "機械仕掛けのバイオリニスト",
            "重力を操る者",
            "孤独な幻術師",
            "ベールに包まれた超能力者",
            "装甲をまとう遊女",
            "都会の魔女",
            "天界の預言者",
            "魔法の刺青師",
            "念動力を持つ神童",
            "異星の外交官",
            "家出した貴族の後継者",
            "デジタル死霊術師"
        ],
        "mapping": {
            "謎めいた魔術師": "mysterious sorcerer",
            "サイボーグ暗殺者": "cybernetic assassin",
            "優雅なバレリーナ": "graceful ballerina",
            "退役した兵士": "retired soldier",
            "物憂げな詩人": "melancholy poet",
            "ゴシックな貴婦人": "gothic noblewoman",
            "砂漠を彷徨う旅人": "desert wanderer",
            "呪われた剣士": "cursed swordsman",
            "未来的なパイロット": "futuristic pilot",
            "スチームパンク整備士": "steampunk mechanic",
            "盲目の予言者": "blind prophet",
            "復讐に燃える霊": "vengeful spirit",
            "路上のマジシャン": "street magician",
            "量子ハッカー": "quantum hacker",
            "不死の神官": "undead priest",
            "アンドロイド護衛": "android bodyguard",
            "王家の側近": "royal advisor",
            "エリート狙撃手": "elite sniper",
            "時空の旅人": "time traveler",
            "ゴシックなギタリスト": "gothic guitarist",
            "夢見る図書館司書": "dreamy librarian",
            "呪われた錬金術師": "cursed alchemist",
            "都会の忍者": "urban ninja",
            "高位の巫女": "high priestess",
            "失墜した騎士": "disgraced knight",
            "テレパシー能力を持つ子供": "telepathic child",
            "吸血鬼の貴族": "vampire noble",
            "部族のシャーマン": "tribal shaman",
            "星間を逃げる逃亡者": "interstellar fugitive",
            "氷の魔術師": "ice mage",
            "悪魔狩人": "demon hunter",
            "森の精霊導師": "forest spirit guide",
            "神秘的な僧侶": "mystical monk",
            "クローン実験体": "clone experiment",
            "反逆の王女": "rogue princess",
            "闘技場の剣闘士": "arena gladiator",
            "霊に取り憑かれたバイオリニスト": "haunted violinist",
            "戦闘用アンドロイド": "battle android",
            "忘れられた王位継承者": "forgotten heir",
            "魂の収集者": "soul collector",
            "呪いを受けた考古学者": "cursed archaeologist",
            "水中のスパイ": "underwater spy",
            "影の工作員": "shadowy agent",
            "念動力の戦士": "telekinetic warrior",
            "心を読む科学者": "mind-reading scientist",
            "仮面の反乱軍リーダー": "masked rebel leader",
            "幽霊船の船長": "ghost ship captain",
            "幻術の使い手": "illusionist performer",
            "無法のガンマン": "outlaw gunslinger",
            "ペスト医師": "plague doctor",
            "逃走中のアンドロイド": "runaway android",
            "戦傷を負った退役軍人": "battle-scarred veteran",
            "仮面の自警団員": "masked vigilante",
            "ゴシックな舞踏家": "gothic dancer",
            "星から追放された者": "exile from the stars",
            "ドラゴンの調教師": "dragon tamer",
            "呪われた王子": "cursed prince",
            "炎の魔女": "flame sorceress",
            "記憶を奪う者": "memory thief",
            "盲目の女剣士": "blind swordswoman",
            "神秘的なハッカー": "mystic hacker",
            "超能力探偵": "psychic detective",
            "堕天使": "fallen angel",
            "夢の解読者": "dream interpreter",
            "人形に取り憑かれた使い手": "haunted puppet master",
            "霊媒師": "spirit medium",
            "装甲の戦術家": "armored tactician",
            "機械仕掛けの発明家": "mechanical inventor",
            "貴族の替え玉": "noble body double",
            "月の巫女": "moon priestess",
            "宇宙船の航行士": "starship navigator",
            "裏切られた将軍": "betrayed general",
            "霊の囁きを聞く者": "ghost whisperer",
            "量子空間の旅人": "quantum traveler",
            "感情を失ったアンドロイド": "emotionless android",
            "孤独な天文学者": "lonely astronomer",
            "不死の放浪者": "immortal wanderer",
            "次元を渡る者": "dimension jumper",
            "氷上の舞姫": "ice dancer",
            "操られた兵士": "mind-controlled soldier",
            "猫の目を持つ盗賊": "cat-eyed thief",
            "呪われた音楽家": "cursed musician",
            "高貴な祓魔師": "noble exorcist",
            "クローンの反乱リーダー": "clone resistance leader",
            "魔女狩り師": "witch hunter",
            "裏切られた王国の守護者": "betrayed royal guard",
            "異種混血の人間": "hybrid human",
            "魔法使いの無法者": "magician outlaw",
            "機械仕掛けのバイオリニスト": "mechanical violinist",
            "重力を操る者": "gravity manipulator",
            "孤独な幻術師": "lonely illusionist",
            "ベールに包まれた超能力者": "veiled psychic",
            "装甲をまとう遊女": "armored courtesan",
            "都会の魔女": "urban witch",
            "天界の預言者": "celestial oracle",
            "魔法の刺青師": "magical tattoo artist",
            "念動力を持つ神童": "telekinetic child prodigy",
            "異星の外交官": "alien diplomat",
            "家出した貴族の後継者": "runaway noble heir",
            "デジタル死霊術師": "digital necromancer"
        },
        "add_comma": True
    },
    {
        "label": "キャラ3",
        "options": [
            "サイボーグの少女",
            "アンドロイドの少年",
            "ミュータントのヒーロー",
            "吸血鬼ハンター",
            "スチームパンク風の冒険者",
            "未来的な兵士",
            "闇の魔術師",
            "光の魔女",
            "アンデッドの戦士",
            "天界の騎士",
            "毒を操る悪役",
            "幽霊の子供",
            "ドラゴン退治の戦士",
            "サイバーニンジャ",
            "メカのパイロット",
            "砂漠を旅する遊牧民",
            "海の巫女",
            "嵐を操る者",
            "疫病医師",
            "魔獣使い",
            "魔王の女王",
            "天使の使者",
            "精霊の守護者",
            "怪盗ファントム",
            "魔導学者",
            "戦う僧侶",
            "森の守護者",
            "バイオ技術の盗賊",
            "幻術使いの少女",
            "エネルギーライフルの狙撃手",
            "炎の踊り子",
            "氷の暗殺者",
            "重力を操る者",
            "量子ハッカー",
            "テクノ音楽の吟遊詩人",
            "反逆の姫君",
            "戦争で傷ついた古参兵",
            "神獣のハーフ",
            "夢を渡る旅人",
            "月光の弓使い",
            "星明かりの聖職者",
            "紅の侍",
            "刃を持つ踊り手",
            "毒に染まった盗賊",
            "仮面の預言者",
            "サイボーグの双子",
            "放射能を帯びたミュータント",
            "時空を彷徨う者",
            "宇宙を漂う旅人",
            "鏡の魔術師",
            "アークリアクター戦士",
            "忘れられた王子",
            "堕ちた聖騎士",
            "仮面の自警団員",
            "ネオンサムライ",
            "夢をハックする者",
            "神話の双子",
            "霊体の踊り子",
            "毒の錬金術師",
            "精霊召喚士",
            "異次元の守護者",
            "残響の騎士",
            "悪夢の獣",
            "月の剣士",
            "ルーンの魔女",
            "幽霊に取り憑かれた歌姫",
            "太陽の聖戦士",
            "テクノロジーの召喚師",
            "デジタルの預言者",
            "混沌の魔法使い",
            "銀河の騎士",
            "火山の戦士",
            "地下の反逆者",
            "魔法のエンジニア",
            "星雲の魔女",
            "オーロラの狙撃手",
            "嵐の悪魔",
            "鉄の賢者",
            "森の魔女",
            "荒れ地の旅人",
            "嵐の心を持つ英雄",
            "ドット絵の盗賊",
            "アーケードの騎士",
            "魂のハッカー",
            "響きの暗殺者",
            "異界の刃",
            "精霊の狐",
            "古代のドルイド",
            "デジタルの獣",
            "幽霊の騎士",
            "幽霊の侍",
            "無線の戦士",
            "太陽の狐",
            "重力の騎士",
            "霧の歩行者",
            "鏡の盗賊",
            "時の巫女",
            "光の狩人",
            "電脳アイドル",
            "魂の騎士"
        ],
        "mapping": {
            "サイボーグの少女": "cyborg girl",
            "アンドロイドの少年": "android boy",
            "ミュータントのヒーロー": "mutant hero",
            "吸血鬼ハンター": "vampire hunter",
            "スチームパンク風の冒険者": "steampunk adventurer",
            "未来的な兵士": "futuristic soldier",
            "闇の魔術師": "dark magician",
            "光の魔女": "light sorceress",
            "アンデッドの戦士": "undead warrior",
            "天界の騎士": "celestial knight",
            "毒を操る悪役": "toxic villain",
            "幽霊の子供": "ghost child",
            "ドラゴン退治の戦士": "dragon slayer",
            "サイバーニンジャ": "cyber ninja",
            "メカのパイロット": "mecha pilot",
            "砂漠を旅する遊牧民": "desert nomad",
            "海の巫女": "oceanic priestess",
            "嵐を操る者": "storm controller",
            "疫病医師": "plague doctor",
            "魔獣使い": "beast tamer",
            "魔王の女王": "demon queen",
            "天使の使者": "angelic messenger",
            "精霊の守護者": "elemental guardian",
            "怪盗ファントム": "phantom thief",
            "魔導学者": "arcane scholar",
            "戦う僧侶": "battle monk",
            "森の守護者": "forest ranger",
            "バイオ技術の盗賊": "biotech rogue",
            "幻術使いの少女": "illusionist girl",
            "エネルギーライフルの狙撃手": "energy sniper",
            "炎の踊り子": "fire dancer",
            "氷の暗殺者": "ice assassin",
            "重力を操る者": "gravity bender",
            "量子ハッカー": "quantum hacker",
            "テクノ音楽の吟遊詩人": "techno bard",
            "反逆の姫君": "rebel princess",
            "戦争で傷ついた古参兵": "war-torn veteran",
            "神獣のハーフ": "sacred beast hybrid",
            "夢を渡る旅人": "dream traveler",
            "月光の弓使い": "moonlight archer",
            "星明かりの聖職者": "starlight cleric",
            "紅の侍": "crimson samurai",
            "刃を持つ踊り手": "bladed dancer",
            "毒に染まった盗賊": "poisoned rogue",
            "仮面の預言者": "masked prophet",
            "サイボーグの双子": "cybernetic twin",
            "放射能を帯びたミュータント": "radioactive mutant",
            "時空を彷徨う者": "space-time wanderer",
            "宇宙を漂う旅人": "cosmic drifter",
            "鏡の魔術師": "mirror mage",
            "アークリアクター戦士": "arc reactor warrior",
            "忘れられた王子": "forgotten prince",
            "堕ちた聖騎士": "fallen paladin",
            "仮面の自警団員": "masked vigilante",
            "ネオンサムライ": "neon samurai",
            "夢をハックする者": "dream hacker",
            "神話の双子": "mythical twin",
            "霊体の踊り子": "ethereal dancer",
            "毒の錬金術師": "toxic alchemist",
            "精霊召喚士": "spirit summoner",
            "異次元の守護者": "dimensional guardian",
            "残響の騎士": "echo knight",
            "悪夢の獣": "nightmare beast",
            "月の剣士": "lunar swordsman",
            "ルーンの魔女": "rune witch",
            "幽霊に取り憑かれた歌姫": "haunted singer",
            "太陽の聖戦士": "solar crusader",
            "テクノロジーの召喚師": "tech summoner",
            "デジタルの預言者": "digital prophet",
            "混沌の魔法使い": "chaotic enchanter",
            "銀河の騎士": "galactic knight",
            "火山の戦士": "volcanic fighter",
            "地下の反逆者": "underground rebel",
            "魔法のエンジニア": "magic engineer",
            "星雲の魔女": "nebula witch",
            "オーロラの狙撃手": "aurora sniper",
            "嵐の悪魔": "storm demon",
            "鉄の賢者": "iron sage",
            "森の魔女": "forest witch",
            "荒れ地の旅人": "desolate wanderer",
            "嵐の心を持つ英雄": "stormy-hearted hero",
            "ドット絵の盗賊": "pixel rogue",
            "アーケードの騎士": "arcade knight",
            "魂のハッカー": "soul hacker",
            "響きの暗殺者": "echo assassin",
            "異界の刃": "nether blade",
            "精霊の狐": "spirit fox",
            "古代のドルイド": "ancient druid",
            "デジタルの獣": "digital beast",
            "幽霊の騎士": "phantom rider",
            "幽霊の侍": "ghost samurai",
            "無線の戦士": "radio warrior",
            "太陽の狐": "solar fox",
            "重力の騎士": "gravity knight",
            "霧の歩行者": "mist walker",
            "鏡の盗賊": "mirror thief",
            "時の巫女": "time priestess",
            "光の狩人": "light hunter",
            "電脳アイドル": "digital idol",
            "魂の騎士": "soul knight"
        },
        "add_comma": True
    },
    {
        "label": "構図1",
        "options": [
            "クローズアップのポートレート",
            "全身ショット",
            "3/4ビュー",
            "鳥瞰図",
            "虫の目線",
            "横顔",
            "肩越しショット",
            "低い位置からのショット",
            "高い位置からのショット",
            "ワイドショット",
            "ミディアムショット",
            "極端なクローズアップ",
            "ダイナミックアングル",
            "対称的な構図",
            "非対称の構図",
            "三分割法",
            "リーディングライン",
            "フレーミング",
            "ネガティブスペース",
            "浅い被写界深度",
            "深い焦点",
            "逆光",
            "シルエット",
            "分割光",
            "リムライト",
            "ソフトライティング",
            "ハーシュライティング",
            "自然光",
            "人工光",
            "スポットライト",
            "ボケ効果",
            "モーションブラー",
            "多重露光",
            "反射",
            "対称反射",
            "歪んだ遠近法",
            "魚眼レンズ効果",
            "パノラマビュー",
            "広角ショット",
            "望遠ショット",
            "ローキーライティング",
            "ハイキーライティング",
            "キアロスクーロ（明暗対比）",
            "ゴールデンアワーの光",
            "ブルーアワーの光",
            "ネオン照明",
            "ろうそくの光",
            "水中ショット",
            "空撮",
            "マクロショット",
            "チルトシフト効果",
            "ダッチアングル",
            "パノラマショット",
            "ヴィネット効果",
            "魚眼遠近法",
            "過露出ショット",
            "露出不足ショット",
            "ソフトフォーカス",
            "ハードフォーカス",
            "ズームバースト",
            "スプリットトーニング",
            "モノクロ",
            "デュオトーン",
            "シルエットショット",
            "後ろ姿ショット",
            "スナップショット",
            "ステージショット",
            "集団ショット",
            "環境ポートレート",
            "ヘッドショット",
            "アクションショット",
            "モーションフリーズ",
            "スローシャッター",
            "パノラマ風景",
            "対称建築",
            "抽象構図",
            "ミニマリズム",
            "シュールな構図",
            "レイヤード構図",
            "奥行きのあるレイヤリング",
            "シネマティックショット",
            "ファンタジー構図",
            "ドラマチック構図",
            "ストーリーテリング構図",
            "ビジュアルナラティブ",
            "焦点強調",
            "動きの強調",
            "緊張感のある構図",
            "バランスの取れた構図",
            "コントラストのある構図",
            "ハーモニーのある構図",
            "ビジュアルリズム",
            "黄金比",
            "ダイナミックフレーミング",
            "型破りなフレーミング",
            "極端な広角ショット",
            "極端なクローズアップショット"
        ],
        "mapping": {
            "クローズアップのポートレート": "close-up portrait",
            "全身ショット": "full body shot",
            "3/4ビュー": "three-quarter view",
            "鳥瞰図": "bird’s-eye view",
            "虫の目線": "worm’s-eye view",
            "横顔": "side profile",
            "肩越しショット": "over-the-shoulder shot",
            "低い位置からのショット": "low angle shot",
            "高い位置からのショット": "high angle shot",
            "ワイドショット": "wide shot",
            "ミディアムショット": "medium shot",
            "極端なクローズアップ": "extreme close-up",
            "ダイナミックアングル": "dynamic angle",
            "対称的な構図": "symmetrical composition",
            "非対称の構図": "asymmetrical composition",
            "三分割法": "rule of thirds",
            "リーディングライン": "leading lines",
            "フレーミング": "framing",
            "ネガティブスペース": "negative space",
            "浅い被写界深度": "shallow depth of field",
            "深い焦点": "deep focus",
            "逆光": "backlighting",
            "シルエット": "silhouette",
            "分割光": "split lighting",
            "リムライト": "rim lighting",
            "ソフトライティング": "soft lighting",
            "ハーシュライティング": "harsh lighting",
            "自然光": "natural light",
            "人工光": "artificial light",
            "スポットライト": "spotlight",
            "ボケ効果": "bokeh effect",
            "モーションブラー": "motion blur",
            "多重露光": "double exposure",
            "反射": "reflection",
            "対称反射": "symmetrical reflection",
            "歪んだ遠近法": "distorted perspective",
            "魚眼レンズ効果": "fisheye lens effect",
            "パノラマビュー": "panoramic view",
            "広角ショット": "wide-angle shot",
            "望遠ショット": "telephoto shot",
            "ローキーライティング": "low key lighting",
            "ハイキーライティング": "high key lighting",
            "キアロスクーロ（明暗対比）": "chiaroscuro",
            "ゴールデンアワーの光": "golden hour lighting",
            "ブルーアワーの光": "blue hour lighting",
            "ネオン照明": "neon lighting",
            "ろうそくの光": "candlelight",
            "水中ショット": "underwater shot",
            "空撮": "aerial shot",
            "マクロショット": "macro shot",
            "チルトシフト効果": "tilt-shift effect",
            "ダッチアングル": "Dutch angle",
            "パノラマショット": "panoramic shot",
            "ヴィネット効果": "vignette effect",
            "魚眼遠近法": "fisheye perspective",
            "過露出ショット": "overexposed shot",
            "露出不足ショット": "underexposed shot",
            "ソフトフォーカス": "soft focus",
            "ハードフォーカス": "hard focus",
            "ズームバースト": "zoom burst",
            "スプリットトーニング": "split toning",
            "モノクロ": "monochrome",
            "デュオトーン": "duotone",
            "シルエットショット": "silhouette shot",
            "後ろ姿ショット": "back shot",
            "スナップショット": "candid shot",
            "ステージショット": "staged shot",
            "集団ショット": "group shot",
            "環境ポートレート": "environmental portrait",
            "ヘッドショット": "headshot",
            "アクションショット": "action shot",
            "モーションフリーズ": "freeze motion",
            "スローシャッター": "slow shutter",
            "パノラマ風景": "panoramic landscape",
            "対称建築": "symmetrical architecture",
            "抽象構図": "abstract composition",
            "ミニマリズム": "minimalism",
            "シュールな構図": "surreal composition",
            "レイヤード構図": "layered composition",
            "奥行きのあるレイヤリング": "depth layering",
            "シネマティックショット": "cinematic shot",
            "ファンタジー構図": "fantasy composition",
            "ドラマチック構図": "dramatic composition",
            "ストーリーテリング構図": "storytelling composition",
            "ビジュアルナラティブ": "visual narrative",
            "焦点強調": "focal point emphasis",
            "動きの強調": "motion emphasis",
            "緊張感のある構図": "tension in composition",
            "バランスの取れた構図": "balance in composition",
            "コントラストのある構図": "contrast in composition",
            "ハーモニーのある構図": "harmony in composition",
            "ビジュアルリズム": "visual rhythm",
            "黄金比": "golden ratio",
            "ダイナミックフレーミング": "dynamic framing",
            "型破りなフレーミング": "unconventional framing",
            "極端な広角ショット": "extreme wide shot",
            "極端なクローズアップショット": "extreme close-up shot"
        },
        "add_comma": True
    },
    {
        "label": "構図2",
        "options": [
            "中心構図",
            "対角線構図",
            "放射状構図",
            "三角構図",
            "フレーミングを活用した構図",
            "シンメトリー構図",
            "非対称バランス",
            "リズミカルな構図",
            "パターンの強調",
            "繰り返しの構図",
            "負の空間を活かした構図",
            "線対称",
            "不均衡な構図",
            "階層的構図",
            "奥行きのある遠近法",
            "シンプルな構図",
            "複雑な構図",
            "対比を生かした構図",
            "垂直ラインの強調",
            "水平ラインの強調",
            "ジグザグライン構図",
            "カーブラインの構図",
            "目線誘導線",
            "境界線の活用",
            "ネガティブスペースを囲む構図",
            "光と影のコントラスト構図",
            "視線の交差点を意識した構図",
            "パースペクティブの強調",
            "中央集約型構図",
            "アンバランスな配置",
            "三角形の配置",
            "分割線を使った構図",
            "動きのある構図",
            "静的な構図",
            "斜めのラインを活かした構図",
            "重なり合うレイヤー構図",
            "層構造の強調",
            "連続性のある構図",
            "クローズアップと背景の対比",
            "空間の余白を活かした構図",
            "対称的なフレーミング",
            "自然物を取り入れた構図",
            "建築物を活かした構図",
            "人工物との対比構図",
            "カラーブロック構図",
            "動きの流れを感じる構図",
            "集中線の利用",
            "風景と人物の調和",
            "対角線を活用したダイナミック構図",
            "フォーカルポイントの明確化",
            "目線誘導のためのライン配置",
            "奥行きを感じさせるレイアウト",
            "ミニマルで空間を意識した構図",
            "フィボナッチスパイラルを活用した構図",
            "多層構造の抽象構図",
            "点と線の関係性を強調した構図",
            "グリッドシステムによる整理された構図",
            "自然光の使い方を強調した構図",
            "人工光と影のバランス構図",
            "映り込みを活かした構図",
            "対称と非対称の融合構図",
            "前景・中景・背景の明確な分割構図",
            "視線の流れを作るレイアウト",
            "レイヤーの重なりで深みを出す構図",
            "複数の焦点を持つ構図",
            "リズム感のあるライン配置",
            "静と動のコントラスト構図",
            "ドラマチックな光の当て方を強調",
            "被写体の配置を対比的にした構図",
            "カメラ目線を強調した構図",
            "動きの連続性を感じる構図",
            "幾何学的形状を活用した構図",
            "対称的な自然風景の構図",
            "抽象的な形と色のバランス構図",
            "動きと静けさの共存構図",
            "光のグラデーションを活かした構図",
            "空間の奥行きを強調した構図",
            "色彩の対比を活かした構図",
            "質感の違いを見せる構図",
            "遠近感を強調した構図",
            "重なり合うシルエット構図",
            "繊細な線の使い方を強調した構図",
            "動きの流れを感じる構図",
            "視覚的なアクセントのある構図",
            "集中線で視線を誘導する構図",
            "背景と前景のバランス構図",
            "複数の被写体を効果的に配置した構図",
            "視線の動きをコントロールした構図",
            "光と影のドラマチックな構図",
            "モノクロで質感を際立たせた構図",
            "カラフルな配色を活かした構図",
            "パターンとリズムの調和構図",
            "レイヤーの透過を使った構図",
            "遠近法を強調した構図",
            "動きの瞬間を捉えた構図",
            "静的な安定感のある構図",
            "自然な視線誘導の構図",
            "被写体の存在感を強調した構図",
            "背景のボケを活かした構図",
            "光源を意識した構図",
            "躍動感のあるライン構図",
            "幾何学的パターンの構図",
            "余白を効果的に使った構図",
            "視線を誘導する色彩構図",
            "大胆なアングルの構図",
            "レイヤー重なりの奥行き構図"
        ],
        "mapping": {
            "中心構図": "central composition",
            "対角線構図": "diagonal composition",
            "放射状構図": "radial composition",
            "三角構図": "triangular composition",
            "フレーミングを活用した構図": "framing composition",
            "シンメトリー構図": "symmetry composition",
            "非対称バランス": "asymmetrical balance",
            "リズミカルな構図": "rhythmic composition",
            "パターンの強調": "pattern emphasis",
            "繰り返しの構図": "repetitive composition",
            "負の空間を活かした構図": "negative space composition",
            "線対称": "line symmetry",
            "不均衡な構図": "uneven composition",
            "階層的構図": "hierarchical composition",
            "奥行きのある遠近法": "deep perspective",
            "シンプルな構図": "simple composition",
            "複雑な構図": "complex composition",
            "対比を生かした構図": "contrast composition",
            "垂直ラインの強調": "vertical line emphasis",
            "水平ラインの強調": "horizontal line emphasis",
            "ジグザグライン構図": "zigzag line composition",
            "カーブラインの構図": "curved line composition",
            "目線誘導線": "leading gaze lines",
            "境界線の活用": "boundary utilization",
            "ネガティブスペースを囲む構図": "negative space framing",
            "光と影のコントラスト構図": "light and shadow contrast",
            "視線の交差点を意識した構図": "intersection gaze composition",
            "パースペクティブの強調": "perspective emphasis",
            "中央集約型構図": "centralized composition",
            "アンバランスな配置": "unbalanced arrangement",
            "三角形の配置": "triangular arrangement",
            "分割線を使った構図": "division line composition",
            "動きのある構図": "dynamic composition",
            "静的な構図": "static composition",
            "斜めのラインを活かした構図": "diagonal line utilization",
            "重なり合うレイヤー構図": "overlapping layers composition",
            "層構造の強調": "layered structure emphasis",
            "連続性のある構図": "continuous composition",
            "クローズアップと背景の対比": "close-up and background contrast",
            "空間の余白を活かした構図": "use of space and margin",
            "対称的なフレーミング": "symmetrical framing",
            "自然物を取り入れた構図": "natural elements composition",
            "建築物を活かした構図": "architecture composition",
            "人工物との対比構図": "contrast with man-made objects",
            "カラーブロック構図": "color block composition",
            "動きの流れを感じる構図": "flowing movement composition",
            "集中線の利用": "use of converging lines",
            "風景と人物の調和": "harmony of landscape and person",
            "対角線を活用したダイナミック構図": "dynamic diagonal composition",
            "フォーカルポイントの明確化": "focal point clarity",
            "目線誘導のためのライン配置": "line placement for gaze guidance",
            "奥行きを感じさせるレイアウト": "layout with depth",
            "ミニマルで空間を意識した構図": "minimal and spatial composition",
            "フィボナッチスパイラルを活用した構図": "Fibonacci spiral composition",
            "多層構造の抽象構図": "multi-layered abstract composition",
            "点と線の関係性を強調した構図": "point and line relationship emphasis",
            "グリッドシステムによる整理された構図": "grid system composition",
            "自然光の使い方を強調した構図": "natural light emphasis",
            "人工光と影のバランス構図": "artificial light and shadow balance",
            "映り込みを活かした構図": "reflection utilization",
            "対称と非対称の融合構図": "symmetry and asymmetry fusion",
            "前景・中景・背景の明確な分割構図": "clear foreground, midground, background division",
            "視線の流れを作るレイアウト": "layout guiding gaze flow",
            "レイヤーの重なりで深みを出す構図": "depth with overlapping layers",
            "複数の焦点を持つ構図": "multiple focal points composition",
            "リズム感のあるライン配置": "rhythmic line placement",
            "静と動のコントラスト構図": "contrast of stillness and motion",
            "ドラマチックな光の当て方を強調": "dramatic lighting emphasis",
            "被写体の配置を対比的にした構図": "contrasting subject placement",
            "カメラ目線を強調した構図": "emphasized camera gaze",
            "動きの連続性を感じる構図": "continuous movement composition",
            "幾何学的形状を活用した構図": "geometric shape composition",
            "対称的な自然風景の構図": "symmetrical natural landscape",
            "抽象的な形と色のバランス構図": "abstract shape and color balance",
            "動きと静けさの共存構図": "coexistence of motion and calm",
            "光のグラデーションを活かした構図": "light gradient utilization",
            "空間の奥行きを強調した構図": "emphasized spatial depth",
            "色彩の対比を活かした構図": "color contrast utilization",
            "質感の違いを見せる構図": "texture contrast composition",
            "遠近感を強調した構図": "emphasized perspective",
            "重なり合うシルエット構図": "overlapping silhouette composition",
            "繊細な線の使い方を強調した構図": "delicate line emphasis",
            "動きの流れを感じる構図": "flowing movement composition",
            "視覚的なアクセントのある構図": "visual accent composition",
            "集中線で視線を誘導する構図": "converging lines for gaze guidance",
            "背景と前景のバランス構図": "background and foreground balance",
            "複数の被写体を効果的に配置した構図": "effective multi-subject composition",
            "視線の動きをコントロールした構図": "controlled gaze movement composition",
            "光と影のドラマチックな構図": "dramatic light and shadow composition",
            "モノクロで質感を際立たせた構図": "monochrome texture emphasis",
            "カラフルな配色を活かした構図": "colorful palette composition",
            "パターンとリズムの調和構図": "pattern and rhythm harmony",
            "レイヤーの透過を使った構図": "transparency layers composition",
            "遠近法を強調した構図": "emphasized perspective technique",
            "動きの瞬間を捉えた構図": "captured motion moment",
            "静的な安定感のある構図": "static stability composition",
            "自然な視線誘導の構図": "natural gaze guidance",
            "被写体の存在感を強調した構図": "subject presence emphasis",
            "背景のボケを活かした構図": "background bokeh utilization",
            "光源を意識した構図": "light source aware composition",
            "躍動感のあるライン構図": "dynamic line composition",
            "幾何学的パターンの構図": "geometric pattern composition",
            "余白を効果的に使った構図": "effective use of margins",
            "視線を誘導する色彩構図": "color composition guiding gaze",
            "大胆なアングルの構図": "bold angle composition",
            "レイヤー重なりの奥行き構図": "layer overlap depth composition"
        },
        "add_comma": True
    },
    {
        "label": "構図3",
        "options": [
            "中央寄せの構図",
            "三分割法を意識した構図",
            "黄金比を使った配置",
            "シンメトリーを活かした構図",
            "不均衡で動きを感じる構図",
            "上下に分割した構図",
            "左右に分割した構図",
            "対角線を意識した配置",
            "放射状に広がる構図",
            "レイヤーで奥行きを出す構図",
            "背景をぼかして被写体を強調",
            "前景をぼかして遠近感を演出",
            "自然のラインを活かした構図",
            "人工的なラインを活かした構図",
            "連続するパターンを使った構図",
            "動きを感じる斜め構図",
            "水平線を活かした広がりのある構図",
            "垂直線で安定感を出した構図",
            "繰り返しのリズムを感じる構図",
            "視線誘導を利用した構図",
            "空間を大きく使ったミニマリズム構図",
            "被写体の視線方向に空間を作る構図",
            "広角で遠近感を強調した構図",
            "望遠で圧縮効果を使った構図",
            "フレーム内フレーム構図",
            "ズームインした迫力のある構図",
            "ズームアウトして全体を見せる構図",
            "光と影のコントラストを強調した構図",
            "反射を使った対称構図",
            "動きのある曲線を活かした構図",
            "シンプルで洗練された構図",
            "複雑なジオメトリックパターン構図",
            "背景と被写体の色彩対比を活かした構図",
            "遠近法を利用した奥行き感のある構図",
            "多重露光のような重なり構図",
            "部分的に切り取ったクロップ構図",
            "広がる線を意識した構図",
            "対称性を崩した意図的なズレ構図",
            "フレアを活用した幻想的な構図",
            "動きのあるシルエット構図",
            "人物のポーズを強調した構図",
            "自然光を活かした柔らかい構図",
            "人工光を使ったドラマチックな構図",
            "色のグラデーションを使った構図",
            "モノクロで陰影を強調した構図",
            "上下の空間バランスを活かした構図",
            "左右の空間バランスを活かした構図",
            "被写体の一部を大胆に切り取った構図",
            "動線を意識した視覚誘導構図",
            "空間の層を強調した構図",
            "パースペクティブを活用した遠近感構図",
            "高い位置からの俯瞰構図",
            "低い位置からのあおり構図",
            "広がりを感じるパノラマ構図",
            "狭い空間を活かした密集感のある構図",
            "グリッドを使った整然とした構図",
            "自然な曲線を活かした柔らかい構図",
            "交差するラインを強調した構図",
            "斜めラインで動きを感じさせる構図",
            "波状のラインを使ったリズミカルな構図",
            "放射線を意識した中心集中構図",
            "水平軸の繰り返しパターン構図",
            "垂直軸の繰り返しパターン構図",
            "ズーム効果で主題を際立たせた構図",
            "シンプルで洗練されたミニマリズム構図",
            "多様なテクスチャを活かした構図",
            "光の反射を使った幻想的な構図",
            "背景にパターンを取り入れた構図",
            "フレームの一部を大胆に使った構図",
            "被写体を画面端に配置した構図",
            "複数の被写体をバランスよく配置した構図",
            "色彩の対比を活かしたダイナミック構図",
            "遠近法で強調した縦長構図",
            "遠近法で強調した横長構図",
            "点対称の整然とした構図",
            "連続する影のパターンを活かした構図",
            "背景のボケ味を活かした構図",
            "空間のリズムを感じさせる構図",
            "複数の視点を組み合わせた構図",
            "空間の広がりを感じる開放的な構図",
            "ジオメトリックな形を組み合わせた構図",
            "光と影の対比を強調したドラマチックな構図",
            "シルエットを使った印象的な構図",
            "輪郭線を強調した構図",
            "動きを感じる曲線のライン構図",
            "色のグラデーションを活かした柔らかい構図",
            "人物の動きを強調した構図",
            "背景と被写体の重なりを活かした構図",
            "視線を誘導するラインを使った構図",
            "自然物の形を活かした構図",
            "人工物のラインを活かした構図",
            "交差点を強調した構図",
            "背景のテクスチャを活かした構図",
            "前景のぼかしを使った奥行き感のある構図",
            "人物の視線を活かした空間配置構図",
            "動きのあるシルエット構図",
            "高いコントラストを活かした構図",
            "グラデーションを使った色彩構図",
            "自然な光の流れを活かした構図",
            "重なりを活かした多層構図"
        ],
        "mapping": {
            "中央寄せの構図": "centered composition",
            "三分割法を意識した構図": "rule of thirds composition",
            "黄金比を使った配置": "golden ratio placement",
            "シンメトリーを活かした構図": "symmetrical composition",
            "不均衡で動きを感じる構図": "asymmetrical dynamic composition",
            "上下に分割した構図": "top-bottom split composition",
            "左右に分割した構図": "left-right split composition",
            "対角線を意識した配置": "diagonal placement",
            "放射状に広がる構図": "radial spread composition",
            "レイヤーで奥行きを出す構図": "layered depth composition",
            "背景をぼかして被写体を強調": "background blur to emphasize subject",
            "前景をぼかして遠近感を演出": "foreground blur to create depth",
            "自然のラインを活かした構図": "composition using natural lines",
            "人工的なラインを活かした構図": "composition using artificial lines",
            "連続するパターンを使った構図": "composition with repeating patterns",
            "動きを感じる斜め構図": "dynamic diagonal composition",
            "水平線を活かした広がりのある構図": "composition emphasizing horizon line",
            "垂直線で安定感を出した構図": "composition emphasizing vertical lines",
            "繰り返しのリズムを感じる構図": "composition with rhythmic repetition",
            "視線誘導を利用した構図": "composition using gaze direction",
            "空間を大きく使ったミニマリズム構図": "minimalist composition using space",
            "被写体の視線方向に空間を作る構図": "composition with space in gaze direction",
            "広角で遠近感を強調した構図": "wide-angle perspective composition",
            "望遠で圧縮効果を使った構図": "telephoto compression composition",
            "フレーム内フレーム構図": "frame within a frame composition",
            "ズームインした迫力のある構図": "zoom-in dramatic composition",
            "ズームアウトして全体を見せる構図": "zoom-out wide composition",
            "光と影のコントラストを強調した構図": "composition emphasizing light-shadow contrast",
            "反射を使った対称構図": "symmetrical composition using reflections",
            "動きのある曲線を活かした構図": "composition using flowing curves",
            "シンプルで洗練された構図": "simple and refined composition",
            "複雑なジオメトリックパターン構図": "complex geometric pattern composition",
            "背景と被写体の色彩対比を活かした構図": "composition with color contrast between background and subject",
            "遠近法を利用した奥行き感のある構図": "perspective composition with depth",
            "多重露光のような重なり構図": "multiple exposure style overlapping composition",
            "部分的に切り取ったクロップ構図": "cropped partial composition",
            "広がる線を意識した構図": "composition emphasizing spreading lines",
            "対称性を崩した意図的なズレ構図": "deliberate asymmetry composition",
            "フレアを活用した幻想的な構図": "composition with lens flare effects",
            "動きのあるシルエット構図": "dynamic silhouette composition",
            "人物のポーズを強調した構図": "composition emphasizing subject's pose",
            "自然光を活かした柔らかい構図": "soft composition using natural light",
            "人工光を使ったドラマチックな構図": "dramatic composition using artificial light",
            "色のグラデーションを使った構図": "composition using color gradients",
            "モノクロで陰影を強調した構図": "monochrome composition emphasizing shadows",
            "上下の空間バランスを活かした構図": "composition with vertical space balance",
            "左右の空間バランスを活かした構図": "composition with horizontal space balance",
            "被写体の一部を大胆に切り取った構図": "boldly cropped subject composition",
            "動線を意識した視覚誘導構図": "composition guiding visual flow",
            "空間の層を強調した構図": "composition emphasizing layers of space",
            "パースペクティブを活用した遠近感構図": "perspective-driven depth composition",
            "高い位置からの俯瞰構図": "bird's-eye view composition",
            "低い位置からのあおり構図": "worm's-eye view composition",
            "広がりを感じるパノラマ構図": "panoramic composition",
            "狭い空間を活かした密集感のある構図": "composition using tight space density",
            "グリッドを使った整然とした構図": "grid-based orderly composition",
            "自然な曲線を活かした柔らかい構図": "soft composition using natural curves",
            "交差するラインを強調した構図": "composition emphasizing intersecting lines",
            "斜めラインで動きを感じさせる構図": "dynamic composition with diagonal lines",
            "波状のラインを使ったリズミカルな構図": "rhythmic composition with wave lines",
            "放射線を意識した中心集中構図": "radial focus composition",
            "水平軸の繰り返しパターン構図": "horizontal repeated pattern composition",
            "垂直軸の繰り返しパターン構図": "vertical repeated pattern composition",
            "ズーム効果で主題を際立たせた構図": "zoom effect highlighting subject",
            "シンプルで洗練されたミニマリズム構図": "simple minimalist composition",
            "多様なテクスチャを活かした構図": "composition with varied textures",
            "光の反射を使った幻想的な構図": "composition with light reflections",
            "背景にパターンを取り入れた構図": "composition incorporating background patterns",
            "フレームの一部を大胆に使った構図": "composition boldly using frame edges",
            "被写体を画面端に配置した構図": "subject placed at screen edge composition",
            "複数の被写体をバランスよく配置した構図": "balanced composition with multiple subjects",
            "色彩の対比を活かしたダイナミック構図": "dynamic composition with color contrasts",
            "遠近法で強調した縦長構図": "vertical perspective composition",
            "遠近法で強調した横長構図": "horizontal perspective composition",
            "点対称の整然とした構図": "point symmetry orderly composition",
            "連続する影のパターンを活かした構図": "composition with repeating shadow patterns",
            "背景のボケ味を活かした構図": "composition using background bokeh",
            "空間のリズムを感じさせる構図": "composition conveying spatial rhythm",
            "複数の視点を組み合わせた構図": "composition combining multiple viewpoints",
            "空間の広がりを感じる開放的な構図": "open composition with spatial expanse",
            "ジオメトリックな形を組み合わせた構図": "composition combining geometric shapes",
            "光と影の対比を強調したドラマチックな構図": "dramatic composition emphasizing light and shadow",
            "シルエットを使った印象的な構図": "impressive silhouette composition",
            "輪郭線を強調した構図": "composition emphasizing outlines",
            "動きを感じる曲線のライン構図": "composition with dynamic curved lines",
            "色のグラデーションを活かした柔らかい構図": "soft composition with color gradients",
            "人物の動きを強調した構図": "composition emphasizing subject motion",
            "背景と被写体の重なりを活かした構図": "composition using background-subject overlap",
            "視線を誘導するラインを使った構図": "composition guiding gaze with lines",
            "自然物の形を活かした構図": "composition using natural shapes",
            "人工物のラインを活かした構図": "composition using artificial lines",
            "交差点を強調した構図": "composition emphasizing intersections",
            "背景のテクスチャを活かした構図": "composition using background texture",
            "前景のぼかしを使った奥行き感のある構図": "composition with blurred foreground for depth",
            "人物の視線を活かした空間配置構図": "composition placing space in subject's gaze direction",
            "動きのあるシルエット構図": "dynamic silhouette composition",
            "高いコントラストを活かした構図": "composition with high contrast",
            "グラデーションを使った色彩構図": "color composition using gradients",
            "自然な光の流れを活かした構図": "composition using natural light flow",
            "重なりを活かした多層構図": "multi-layer composition using overlaps"
        },
        "add_comma": True
    },
    {
        "label": "人物像1",
        "options": [
            "自信に満ちた男性",
            "優雅な女性",
            "若々しい少年",
            "落ち着いた大人",
            "明るい少女",
            "強靭な戦士",
            "知的な科学者",
            "神秘的な魔法使い",
            "陽気な農夫",
            "クールな探偵",
            "繊細な芸術家",
            "自由奔放な冒険者",
            "穏やかな教師",
            "情熱的な音楽家",
            "冷静な指揮官",
            "礼儀正しい紳士",
            "活発な学生",
            "謎めいたスパイ",
            "優しい看護師",
            "大胆な起業家",
            "孤独な詩人",
            "元気な子供",
            "堂々とした騎士",
            "謙虚な僧侶",
            "思慮深い哲学者",
            "感情豊かな俳優",
            "真面目な警察官",
            "大胆なレーサー",
            "理知的な弁護士",
            "純粋な少女",
            "情熱的な画家",
            "静かな忍者",
            "勇敢な消防士",
            "好奇心旺盛な探検家",
            "現代的なダンサー",
            "神聖な僧侶",
            "感謝を忘れない農夫",
            "洗練されたモデル",
            "自立した母親",
            "頼りになる兄貴分",
            "強い絆を持つ友人",
            "穏やかな僧侶",
            "華やかな俳優",
            "クールなメカニック",
            "元気なスポーツ選手",
            "聡明な教師",
            "落ち着いた医者",
            "優雅なバレリーナ",
            "忠実な騎士",
            "大胆な探検家",
            "知性的な作家",
            "素朴な村人",
            "豪快な漁師",
            "誠実な警官",
            "陽気なマジシャン",
            "情熱的なダンサー",
            "慎重な科学者",
            "自由な精神の詩人",
            "大胆な冒険家",
            "優しい母親",
            "知的な学生",
            "熱心なボランティア",
            "冷静なリーダー",
            "朗らかな兄弟",
            "神秘的な預言者",
            "元気な農夫",
            "真面目な司書",
            "力強いレスラー",
            "感情的な恋人",
            "クールなスケーター",
            "陽気なカフェ店員",
            "孤独な画家",
            "大胆な宇宙飛行士",
            "繊細なピアニスト",
            "優雅な詩人",
            "熱血漢のスポーツ選手",
            "気まぐれな旅人",
            "真摯な教師",
            "静かな画家",
            "楽天的な農夫",
            "謙虚な音楽家",
            "情熱的なリーダー",
            "大胆な研究者",
            "思慮深い哲学者",
            "活発な少年",
            "落ち着いた女性",
            "明るい少女",
            "強い意志の男性",
            "自由な精神の少女",
            "勇敢な戦士",
            "礼儀正しい紳士",
            "神秘的な魔法使い",
            "知的な科学者",
            "元気な子供",
            "孤独な詩人",
            "大胆な起業家",
            "優しい看護師",
            "冷静な指揮官",
            "自由奔放な冒険者",
            "感謝を忘れない農夫",
            "クールな探偵",
            "穏やかな教師",
            "情熱的な音楽家"
        ],
        "mapping": {
            "自信に満ちた男性": "confident man",
            "優雅な女性": "elegant woman",
            "若々しい少年": "youthful boy",
            "落ち着いた大人": "calm adult",
            "明るい少女": "cheerful girl",
            "強靭な戦士": "strong warrior",
            "知的な科学者": "intelligent scientist",
            "神秘的な魔法使い": "mysterious magician",
            "陽気な農夫": "cheerful farmer",
            "クールな探偵": "cool detective",
            "繊細な芸術家": "delicate artist",
            "自由奔放な冒険者": "free-spirited adventurer",
            "穏やかな教師": "gentle teacher",
            "情熱的な音楽家": "passionate musician",
            "冷静な指揮官": "calm commander",
            "礼儀正しい紳士": "polite gentleman",
            "活発な学生": "active student",
            "謎めいたスパイ": "mysterious spy",
            "優しい看護師": "kind nurse",
            "大胆な起業家": "bold entrepreneur",
            "孤独な詩人": "lonely poet",
            "元気な子供": "energetic child",
            "堂々とした騎士": "dignified knight",
            "謙虚な僧侶": "humble monk",
            "思慮深い哲学者": "thoughtful philosopher",
            "感情豊かな俳優": "emotional actor",
            "真面目な警察官": "serious police officer",
            "大胆なレーサー": "daring racer",
            "理知的な弁護士": "intellectual lawyer",
            "純粋な少女": "pure girl",
            "情熱的な画家": "passionate painter",
            "静かな忍者": "quiet ninja",
            "勇敢な消防士": "brave firefighter",
            "好奇心旺盛な探検家": "curious explorer",
            "現代的なダンサー": "modern dancer",
            "神聖な僧侶": "holy monk",
            "感謝を忘れない農夫": "grateful farmer",
            "洗練されたモデル": "sophisticated model",
            "自立した母親": "independent mother",
            "頼りになる兄貴分": "reliable older brother",
            "強い絆を持つ友人": "close-knit friend",
            "穏やかな僧侶": "peaceful monk",
            "華やかな俳優": "glamorous actor",
            "クールなメカニック": "cool mechanic",
            "元気なスポーツ選手": "lively athlete",
            "聡明な教師": "wise teacher",
            "落ち着いた医者": "calm doctor",
            "優雅なバレリーナ": "graceful ballerina",
            "忠実な騎士": "loyal knight",
            "大胆な探検家": "bold explorer",
            "知性的な作家": "intelligent writer",
            "素朴な村人": "simple villager",
            "豪快な漁師": "hearty fisherman",
            "誠実な警官": "honest policeman",
            "陽気なマジシャン": "cheerful magician",
            "情熱的なダンサー": "passionate dancer",
            "慎重な科学者": "cautious scientist",
            "自由な精神の詩人": "free-spirited poet",
            "大胆な冒険家": "bold adventurer",
            "優しい母親": "kind mother",
            "知的な学生": "intelligent student",
            "熱心なボランティア": "enthusiastic volunteer",
            "冷静なリーダー": "calm leader",
            "朗らかな兄弟": "cheerful sibling",
            "神秘的な預言者": "mysterious prophet",
            "元気な農夫": "energetic farmer",
            "真面目な司書": "serious librarian",
            "力強いレスラー": "powerful wrestler",
            "感情的な恋人": "emotional lover",
            "クールなスケーター": "cool skater",
            "陽気なカフェ店員": "cheerful cafe staff",
            "孤独な画家": "lonely painter",
            "大胆な宇宙飛行士": "bold astronaut",
            "繊細なピアニスト": "delicate pianist",
            "優雅な詩人": "graceful poet",
            "熱血漢のスポーツ選手": "passionate athlete",
            "気まぐれな旅人": "whimsical traveler",
            "真摯な教師": "earnest teacher",
            "静かな画家": "quiet painter",
            "楽天的な農夫": "optimistic farmer",
            "謙虚な音楽家": "humble musician",
            "情熱的なリーダー": "passionate leader",
            "大胆な研究者": "bold researcher",
            "思慮深い哲学者": "thoughtful philosopher",
            "活発な少年": "active boy",
            "落ち着いた女性": "calm woman",
            "明るい少女": "bright girl",
            "強い意志の男性": "strong-willed man",
            "自由な精神の少女": "free-spirited girl",
            "勇敢な戦士": "brave warrior",
            "礼儀正しい紳士": "polite gentleman",
            "神秘的な魔法使い": "mysterious wizard",
            "知的な科学者": "intelligent scientist",
            "元気な子供": "energetic child",
            "孤独な詩人": "lonely poet",
            "大胆な起業家": "bold entrepreneur",
            "優しい看護師": "kind nurse",
            "冷静な指揮官": "calm commander",
            "自由奔放な冒険者": "free-spirited adventurer",
            "感謝を忘れない農夫": "grateful farmer",
            "クールな探偵": "cool detective",
            "穏やかな教師": "gentle teacher",
            "情熱的な音楽家": "passionate musician"
        },
        "add_comma": True
    },
    {
        "label": "人物像2",
        "options": [
            "冒険を求める探検家",
            "思慮深い哲学者",
            "旅する吟遊詩人",
            "カリスマ的な指導者",
            "内気な本好き",
            "恐れ知らずの戦士",
            "好奇心旺盛な科学者",
            "意志の強いアスリート",
            "風変わりな発明家",
            "夢見る詩人",
            "優しい癒し手",
            "感情を抑えた侍",
            "心優しい魔女",
            "謎めいた探偵",
            "情熱的な芸術家",
            "孤独な旅人",
            "勇敢な騎士",
            "頭の切れる盗賊",
            "献身的な教師",
            "反抗的な若者",
            "気品ある貴族",
            "厳格な指揮官",
            "無垢な子ども",
            "経験豊かな導師",
            "苦悩を抱えた魂",
            "賢明な賢者",
            "陽気なパン職人",
            "冷徹な暗殺者",
            "物静かな観察者",
            "ロマンチストな夢想家",
            "誤解された天才",
            "隠遁生活の僧侶",
            "野心的な起業家",
            "おしゃべりな商人",
            "霊的なシャーマン",
            "忠実な召使い",
            "英雄的な消防士",
            "不機嫌な漁師",
            "高潔な守護者",
            "好奇心旺盛な記者",
            "非情な海賊",
            "ユーモアあふれる道化師",
            "大胆不敵なパイロット",
            "真面目な司書",
            "気ままな旅人",
            "悩める芸術家",
            "思いやりのある医者",
            "復讐に燃える霊",
            "眠そうな学生",
            "信念ある活動家",
            "理想に燃える革命家",
            "老練の戦士",
            "明るい配達員",
            "いたずら好きのトリックスター",
            "正義を求める弁護士",
            "献身的な看護師",
            "派手なパフォーマー",
            "未来的なアンドロイド",
            "ノスタルジックな音楽家",
            "心に傷を負った生存者",
            "感情豊かな俳優",
            "冷静な戦略家",
            "こっそり動くスパイ",
            "疲れた会社員",
            "風変わりな教授",
            "悲劇のヒロイン",
            "穏やかな修道女",
            "自信過剰な天才",
            "魅惑的な幻術師",
            "陰気なバリスタ",
            "自信過剰な騎士",
            "控えめな農民",
            "忍耐強い庭師",
            "自慢げな狩人",
            "集中力のある武道家",
            "忘れっぽい学者",
            "喜びに満ちたダンサー",
            "堅物の銀行員",
            "懐疑的な記者",
            "忠実な護衛",
            "強くたくましい母親",
            "優しいベビーシッター",
            "熱意あるコーチ",
            "勇敢な登山家",
            "恥ずかしがり屋の歌手",
            "情熱的な料理人",
            "予測不能なギャンブラー",
            "探究心旺盛な考古学者",
            "冷酷な貴族",
            "心優しい巨人",
            "せっかちな探偵",
            "戦略家のチェスプレイヤー",
            "詩的な劇作家",
            "たくましい難民",
            "厳格な裁判官",
            "賢い魔術師",
            "落ち着いた書道家",
            "怠け者のゲーマー",
            "悩める夢追い人",
            "正体不明の旅人"
        ],
        "mapping": {
            "冒険を求める探検家": "adventurous explorer",
            "思慮深い哲学者": "thoughtful philosopher",
            "旅する吟遊詩人": "wandering bard",
            "カリスマ的な指導者": "charismatic leader",
            "内気な本好き": "shy bookworm",
            "恐れ知らずの戦士": "fearless warrior",
            "好奇心旺盛な科学者": "curious scientist",
            "意志の強いアスリート": "determined athlete",
            "風変わりな発明家": "eccentric inventor",
            "夢見る詩人": "dreamy poet",
            "優しい癒し手": "gentle healer",
            "感情を抑えた侍": "stoic samurai",
            "心優しい魔女": "kind-hearted witch",
            "謎めいた探偵": "mysterious detective",
            "情熱的な芸術家": "passionate artist",
            "孤独な旅人": "lonely traveler",
            "勇敢な騎士": "brave knight",
            "頭の切れる盗賊": "clever thief",
            "献身的な教師": "devoted teacher",
            "反抗的な若者": "rebellious youth",
            "気品ある貴族": "elegant noble",
            "厳格な指揮官": "stern commander",
            "無垢な子ども": "innocent child",
            "経験豊かな導師": "experienced mentor",
            "苦悩を抱えた魂": "tormented soul",
            "賢明な賢者": "wise sage",
            "陽気なパン職人": "cheerful baker",
            "冷徹な暗殺者": "cold assassin",
            "物静かな観察者": "quiet observer",
            "ロマンチストな夢想家": "romantic dreamer",
            "誤解された天才": "misunderstood genius",
            "隠遁生活の僧侶": "reclusive monk",
            "野心的な起業家": "ambitious entrepreneur",
            "おしゃべりな商人": "talkative merchant",
            "霊的なシャーマン": "spiritual shaman",
            "忠実な召使い": "loyal servant",
            "英雄的な消防士": "heroic firefighter",
            "不機嫌な漁師": "grumpy fisherman",
            "高潔な守護者": "noble guardian",
            "好奇心旺盛な記者": "curious journalist",
            "非情な海賊": "ruthless pirate",
            "ユーモアあふれる道化師": "humorous jester",
            "大胆不敵なパイロット": "fearless pilot",
            "真面目な司書": "serious librarian",
            "気ままな旅人": "carefree traveler",
            "悩める芸術家": "frustrated artist",
            "思いやりのある医者": "compassionate doctor",
            "復讐に燃える霊": "vengeful spirit",
            "眠そうな学生": "sleepy student",
            "信念ある活動家": "determined activist",
            "理想に燃える革命家": "idealistic revolutionary",
            "老練の戦士": "aging warrior",
            "明るい配達員": "cheerful delivery person",
            "いたずら好きのトリックスター": "mischievous trickster",
            "正義を求める弁護士": "justice-seeking lawyer",
            "献身的な看護師": "selfless nurse",
            "派手なパフォーマー": "extravagant performer",
            "未来的なアンドロイド": "futuristic android",
            "ノスタルジックな音楽家": "nostalgic musician",
            "心に傷を負った生存者": "haunted survivor",
            "感情豊かな俳優": "emotional actor",
            "冷静な戦略家": "composed strategist",
            "こっそり動くスパイ": "sneaky spy",
            "疲れた会社員": "tired office worker",
            "風変わりな教授": "eccentric professor",
            "悲劇のヒロイン": "tragic heroine",
            "穏やかな修道女": "serene nun",
            "自信過剰な天才": "egotistical genius",
            "魅惑的な幻術師": "charming illusionist",
            "陰気なバリスタ": "gloomy barista",
            "自信過剰な騎士": "overconfident knight",
            "控えめな農民": "modest farmer",
            "忍耐強い庭師": "patient gardener",
            "自慢げな狩人": "boastful hunter",
            "集中力のある武道家": "focused martial artist",
            "忘れっぽい学者": "absent-minded scholar",
            "喜びに満ちたダンサー": "joyful dancer",
            "堅物の銀行員": "uptight banker",
            "懐疑的な記者": "skeptical journalist",
            "忠実な護衛": "loyal bodyguard",
            "強くたくましい母親": "fierce mother",
            "優しいベビーシッター": "sweet babysitter",
            "熱意あるコーチ": "determined coach",
            "勇敢な登山家": "brave mountaineer",
            "恥ずかしがり屋の歌手": "bashful singer",
            "情熱的な料理人": "passionate chef",
            "予測不能なギャンブラー": "unpredictable gambler",
            "探究心旺盛な考古学者": "curious archaeologist",
            "冷酷な貴族": "cold-hearted noble",
            "心優しい巨人": "gentle giant",
            "せっかちな探偵": "impatient detective",
            "戦略家のチェスプレイヤー": "strategic chess player",
            "詩的な劇作家": "poetic playwright",
            "たくましい難民": "resilient refugee",
            "厳格な裁判官": "stern judge",
            "賢い魔術師": "clever magician",
            "落ち着いた書道家": "calm calligrapher",
            "怠け者のゲーマー": "lazy gamer",
            "悩める夢追い人": "troubled dreamer",
            "正体不明の旅人": "mysterious stranger"
        },
        "add_comma": True
    }
]








comboboxes = []
selected_flags = []

# コンボボックスの作成（2列構成・幅指定）
def on_select(index):
    selected_flags[index] = True

for i, data in enumerate(combo_data):
    values = [data["label"]] + data["options"]
    row = i % 13 + 13
    col = i // 13
    cb = ttk.Combobox(main_win, values=values, width=20)
    cb.grid(row=row, column=col, padx=10, pady=5)
    cb.set(values[0])
    cb.bind("<<ComboboxSelected>>", lambda e, idx=i: on_select(idx))
    comboboxes.append(cb)
    selected_flags.append(False)

def print_text():
    result = []
    for i, cb in enumerate(comboboxes):
        if selected_flags[i]:
            selected = cb.get()
            if selected in combo_data[i]["mapping"]:
                value = combo_data[i]["mapping"][selected]
                if combo_data[i]["add_comma"]:
                    value = "," + value
                result.append(value)
    label.config(text="".join(result))

def copy_text():
    text_to_copy = label.cget("text")
    main_win.clipboard_clear()
    main_win.clipboard_append(text_to_copy)
    messagebox.showinfo("コピー完了", "テキストがコピーされました。")

button_print = tk.Button(main_win, text="表示", command=print_text)
button_print.grid(row=0, column=1, padx=10)

button_copy = tk.Button(main_win, text="コピー", command=copy_text)
button_copy.grid(row=0, column=0, padx=10)

label = tk.Label(main_win)
label.grid(row=2, column=0, columnspan=2, pady=5)

main_win.mainloop()


